package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
)

// User user
// swagger:model User
type User struct {

	// User E-mail address.
	Email string `json:"email,omitempty"`

	// User first name.
	FirstName string `json:"firstName,omitempty"`

	// User ID.
	ID int32 `json:"id,omitempty"`

	// User last name.
	LastName string `json:"lastName,omitempty"`

	// Updated date.
	Updated string `json:"updated,omitempty"`
}

// Validate validates this user
func (m *User) Validate(formats strfmt.Registry) error {
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
