package j_w_t

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/validate"

	strfmt "github.com/go-openapi/strfmt"
)

// NewPostJwtParams creates a new PostJwtParams object
// with the default values initialized.
func NewPostJwtParams() PostJwtParams {
	var ()
	return PostJwtParams{}
}

// PostJwtParams contains all the bound params for the post jwt operation
// typically these are obtained from a http.Request
//
// swagger:parameters PostJwt
type PostJwtParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request

	/*User E-mail.
	  Required: true
	  In: formData
	*/
	InputEmail string
	/*User password.
	  Required: true
	  In: formData
	*/
	InputPassword string
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls
func (o *PostJwtParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error
	o.HTTPRequest = r

	if err := r.ParseMultipartForm(32 << 20); err != nil {
		if err != http.ErrNotMultipart {
			return err
		} else if err := r.ParseForm(); err != nil {
			return err
		}
	}
	fds := runtime.Values(r.Form)

	fdInputEmail, fdhkInputEmail, _ := fds.GetOK("inputEmail")
	if err := o.bindInputEmail(fdInputEmail, fdhkInputEmail, route.Formats); err != nil {
		res = append(res, err)
	}

	fdInputPassword, fdhkInputPassword, _ := fds.GetOK("inputPassword")
	if err := o.bindInputPassword(fdInputPassword, fdhkInputPassword, route.Formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *PostJwtParams) bindInputEmail(rawData []string, hasKey bool, formats strfmt.Registry) error {
	if !hasKey {
		return errors.Required("inputEmail", "formData")
	}
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}
	if err := validate.RequiredString("inputEmail", "formData", raw); err != nil {
		return err
	}

	o.InputEmail = raw

	return nil
}

func (o *PostJwtParams) bindInputPassword(rawData []string, hasKey bool, formats strfmt.Registry) error {
	if !hasKey {
		return errors.Required("inputPassword", "formData")
	}
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}
	if err := validate.RequiredString("inputPassword", "formData", raw); err != nil {
		return err
	}

	o.InputPassword = raw

	return nil
}
