package users

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/errors"
)

// NewGetUsersIdsParams creates a new GetUsersIdsParams object
// with the default values initialized.
func NewGetUsersIdsParams() GetUsersIdsParams {
	var ()
	return GetUsersIdsParams{}
}

// GetUsersIdsParams contains all the bound params for the get users ids operation
// typically these are obtained from a http.Request
//
// swagger:parameters GetUsersIds
type GetUsersIdsParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls
func (o *GetUsersIdsParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error
	o.HTTPRequest = r

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
