package users

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/validate"

	strfmt "github.com/go-openapi/strfmt"
)

// NewPostUsersParams creates a new PostUsersParams object
// with the default values initialized.
func NewPostUsersParams() PostUsersParams {
	var ()
	return PostUsersParams{}
}

// PostUsersParams contains all the bound params for the post users operation
// typically these are obtained from a http.Request
//
// swagger:parameters PostUsers
type PostUsersParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request

	/*User E-mail.
	  Required: true
	  In: formData
	*/
	Email string
	/*User first name.
	  Required: true
	  In: formData
	*/
	FirstName string
	/*User last name.
	  Required: true
	  In: formData
	*/
	LastName string
	/*User password.
	  Required: true
	  In: formData
	*/
	Password string
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls
func (o *PostUsersParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error
	o.HTTPRequest = r

	if err := r.ParseMultipartForm(32 << 20); err != nil {
		if err != http.ErrNotMultipart {
			return err
		} else if err := r.ParseForm(); err != nil {
			return err
		}
	}
	fds := runtime.Values(r.Form)

	fdEmail, fdhkEmail, _ := fds.GetOK("email")
	if err := o.bindEmail(fdEmail, fdhkEmail, route.Formats); err != nil {
		res = append(res, err)
	}

	fdFirstName, fdhkFirstName, _ := fds.GetOK("firstName")
	if err := o.bindFirstName(fdFirstName, fdhkFirstName, route.Formats); err != nil {
		res = append(res, err)
	}

	fdLastName, fdhkLastName, _ := fds.GetOK("lastName")
	if err := o.bindLastName(fdLastName, fdhkLastName, route.Formats); err != nil {
		res = append(res, err)
	}

	fdPassword, fdhkPassword, _ := fds.GetOK("password")
	if err := o.bindPassword(fdPassword, fdhkPassword, route.Formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *PostUsersParams) bindEmail(rawData []string, hasKey bool, formats strfmt.Registry) error {
	if !hasKey {
		return errors.Required("email", "formData")
	}
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}
	if err := validate.RequiredString("email", "formData", raw); err != nil {
		return err
	}

	o.Email = raw

	return nil
}

func (o *PostUsersParams) bindFirstName(rawData []string, hasKey bool, formats strfmt.Registry) error {
	if !hasKey {
		return errors.Required("firstName", "formData")
	}
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}
	if err := validate.RequiredString("firstName", "formData", raw); err != nil {
		return err
	}

	o.FirstName = raw

	return nil
}

func (o *PostUsersParams) bindLastName(rawData []string, hasKey bool, formats strfmt.Registry) error {
	if !hasKey {
		return errors.Required("lastName", "formData")
	}
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}
	if err := validate.RequiredString("lastName", "formData", raw); err != nil {
		return err
	}

	o.LastName = raw

	return nil
}

func (o *PostUsersParams) bindPassword(rawData []string, hasKey bool, formats strfmt.Registry) error {
	if !hasKey {
		return errors.Required("password", "formData")
	}
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}
	if err := validate.RequiredString("password", "formData", raw); err != nil {
		return err
	}

	o.Password = raw

	return nil
}
