package users

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/hiromaily/go-gin-wrapper/swagger/models"
)

/*PutUsersIDOK An array of updated user.

swagger:response putUsersIdOK
*/
type PutUsersIDOK struct {

	/*
	  In: Body
	*/
	Payload *models.Users `json:"body,omitempty"`
}

// NewPutUsersIDOK creates PutUsersIDOK with default headers values
func NewPutUsersIDOK() *PutUsersIDOK {
	return &PutUsersIDOK{}
}

// WithPayload adds the payload to the put users Id o k response
func (o *PutUsersIDOK) WithPayload(payload *models.Users) *PutUsersIDOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the put users Id o k response
func (o *PutUsersIDOK) SetPayload(payload *models.Users) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PutUsersIDOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

/*PutUsersIDDefault Unexpected error.

swagger:response putUsersIdDefault
*/
type PutUsersIDDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewPutUsersIDDefault creates PutUsersIDDefault with default headers values
func NewPutUsersIDDefault(code int) *PutUsersIDDefault {
	if code <= 0 {
		code = 500
	}

	return &PutUsersIDDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the put users ID default response
func (o *PutUsersIDDefault) WithStatusCode(code int) *PutUsersIDDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the put users ID default response
func (o *PutUsersIDDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the put users ID default response
func (o *PutUsersIDDefault) WithPayload(payload *models.Error) *PutUsersIDDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the put users ID default response
func (o *PutUsersIDDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PutUsersIDDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
