package users

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/hiromaily/go-gin-wrapper/swagger/go-swagger/models"
)

/*PostUsersOK An array of user.

swagger:response postUsersOK
*/
type PostUsersOK struct {

	/*
	  In: Body
	*/
	Payload *models.UserID `json:"body,omitempty"`
}

// NewPostUsersOK creates PostUsersOK with default headers values
func NewPostUsersOK() *PostUsersOK {
	return &PostUsersOK{}
}

// WithPayload adds the payload to the post users o k response
func (o *PostUsersOK) WithPayload(payload *models.UserID) *PostUsersOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post users o k response
func (o *PostUsersOK) SetPayload(payload *models.UserID) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostUsersOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

/*PostUsersDefault Unexpected error.

swagger:response postUsersDefault
*/
type PostUsersDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewPostUsersDefault creates PostUsersDefault with default headers values
func NewPostUsersDefault(code int) *PostUsersDefault {
	if code <= 0 {
		code = 500
	}

	return &PostUsersDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the post users default response
func (o *PostUsersDefault) WithStatusCode(code int) *PostUsersDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the post users default response
func (o *PostUsersDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the post users default response
func (o *PostUsersDefault) WithPayload(payload *models.Error) *PostUsersDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post users default response
func (o *PostUsersDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostUsersDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
